### ISSUE TITLE
support for nuxt3

### ISSUE THREAD

**Issue by jnre** [nuxt-community/mdx-module#34]
is there any ongoing support for nuxt3?

**Comment by NyllRE** [comment]
We seriously need nuxt 3 support

**Comment by codebender828** [comment]
Hi @jnre @NyllRE ! Sorry for my delayed response here. Life has been quite busy of late. I'm happy to take a stab at this during the holidays. However, if you need it urgently, I'll gladly review any new pull requests

**Comment by NyllRE** [comment]
@codebender828, well I would be very happy to do so. I just need to know that since it is made for nuxt 2 I should keep the code working for nuxt 2. should I transform it in general to nuxt 3? Just so I understand the way you would like to operate

**Comment by harlan-zw** [comment]
Let's track here: https://github.com/nuxt-community/mdx-module/issues/34 :)
