### ISSUE TITLE
[docs] Add usage and minimum nuxt version 

### ISSUE THREAD

**Issue by pi0** [nuxt-community/mdx-module#6]
It would be nice adding some usage example to main README. Also i think as of `additionalExtensions` usage, some older nuxt versions would partially work. /cc @kevinmarrec i can't recall exact version

**Comment by pi0** [comment]
Extending supported extensions added by nuxt/nuxt.js#5854 via v2.10.0 so it is essentially minimum supported version for this module.

PS: I think now we have docs we can empty main README and link to docs ;)

**Comment by codebender828** [comment]
Noted. Will update the README and link to docs. Thank you! @pi0 @Atinux
